#!/usr/bin/env python3
"""
Serve script for SageMaker inference.

This script starts the model server when the container is invoked for hosting.
"""

import multiprocessing
import os
import signal
import subprocess
import sys

cpu_count = multiprocessing.cpu_count()
model_server_timeout = os.environ.get("MODEL_SERVER_TIMEOUT", 60)
model_server_workers = int(os.environ.get("MODEL_SERVER_WORKERS", cpu_count))


def sigterm_handler(nginx_pid, gunicorn_pid):
    """Handle SIGTERM signal for graceful shutdown."""
    try:
        os.kill(nginx_pid, signal.SIGQUIT)
    except OSError:
        pass
    try:
        os.kill(gunicorn_pid, signal.SIGTERM)
    except OSError:
        pass

    sys.exit(0)


def start_server():
    """Start the inference server."""
    print("Starting the inference server with {} workers.".format(model_server_workers))

    # Start gunicorn server
    subprocess.Popen([
        "gunicorn",
        "--timeout", str(model_server_timeout),
        "--bind", "0.0.0.0:8080",
        "--workers", str(model_server_workers),
        "sagemaker_inference.serving:app"
    ])


if __name__ == "__main__":
    start_server()
